### ISSUE TITLE
Cant find ./syslog

### ISSUE THREAD

**Issue by ghost** [schamane/node-syslog#18]
Hello Syslog team,

i just wanted to mention that you have to change in the node-syslog.js the following line:

var SyslogWrapper = require('./syslog').Syslog;

to 

var SyslogWrapper = require('./build/Release/syslog').Syslog;

Otherwise the module wont run and throw an exception that it cant find ./syslog 

Used Node Version:
Node JS 0.8 

Used OS:
CentOS 6.2 64 bit

Greetings,
Markus

**Comment by till** [comment]
Googled this error and came here.

In the end, it seems like somewhere when I installed `node-syslog` (on Ubuntu), I had no `g++` installed and because it is listed in `optionalDependencies`, it did not fail `npm install node-syslog` hard enough. 

Anyway, `apt-get install g++` and it all worked.
