### ISSUE TITLE
precompiled binaries so that windows doesn't need a million microsoft visual studio installs

### ISSUE THREAD

**Issue by Pomax** [schamane/node-syslog#29]
Borrowing a leaf out of https://github.com/mapbox/node-sqlite3's book of npm modulism, it would be super useful if there were precompiled binairies so that node-gyp never tries to build the code on a windows machine. The amount of compiling software for node-gyp to do its job is staggering (rather than just a gc/gc++ compiler, a full 1GB+ MS Visual C++ stack is necessary), taking that awa with an AWS-hosted binary and only compiling if no platform binary is found would be fantastic.

**Comment by sam-github** [comment]
This is a problem with the user of node-syslog requiring a non-optional module that doesn't work on windows, not lack of a compiler. It can't be fixed here.
