### ISSUE TITLE
unnecessary close() on process exit

### ISSUE THREAD

**Issue by Xubor** [schamane/node-syslog#38]
It is not possible to use Syslog.log() at termination phase of process - during or after 'exit' event.

This is caused by following code:
````
process.on('exit', function() {
    SyslogWrapper.close();
});
````
But the call to `close()` is unnecessary. As stated in `syslog` manpage:
````closelog() closes the descriptor being used to write to the system logger. The use of closelog() is optional. ````
Please remove it.

In the production env of one my application I have no access to the console output (nor I can write to the file). Therefore I resend all messages through syslog and I need to do it also during app termination.

**Comment by sam-github** [comment]
Your reasoning seems sound to me. No idea why the `closelog()` is there. I've removed it in https://github.com/strongloop-forks/strong-fork-syslog/pull/5, please take a look.
