### ISSUE TITLE
Node 12.2 npm 2.7.4, node-gyp 1.0.3 - npm rebuild error

### ISSUE THREAD

**Issue by thxmike** [schamane/node-syslog#43]
When attempting to do an npm rebuild on with an existing node_modules folder, the following error occurs on a Ubuntu 14.04 system:

> node-syslog@1.2.0 install /opt/buildagent/work/d86748d67b9c54a8/Product/src/node_modules/node-syslog
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp verb cli [ 'node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@1.0.3
gyp info using node@0.12.2 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp ERR! clean error 
gyp ERR! stack Error: EACCES, rmdir 'build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 3.13.0-24-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/buildagent/work/d86748d67b9c54a8/Product/src/node_modules/node-syslog
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

npm verb unsafe-perm in lifecycle false
npm info node-syslog@1.2.0 Failed to exec install script
npm verb stack Error: node-syslog@1.2.0 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
npm verb stack     at EventEmitter.emit (events.js:110:17)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
npm verb stack     at ChildProcess.emit (events.js:110:17)
npm verb stack     at maybeClose (child_process.js:1015:16)
npm verb stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
npm verb pkgid node-syslog@1.2.0
npm verb cwd /opt/buildagent/work/d86748d67b9c54a8/Product/src
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "-verbose"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE
npm ERR! node-syslog@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-syslog@1.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-syslog
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/buildagent/work/d86748d67b9c54a8/Product/src/npm-debug.log

npm install runs fine. 

Here is our package.json:
{
    "name": "tes-identity",
    "version": "0.0.1",
    "private": true,
    "scripts": {
        "start": "node app.js"
    },
    "dependencies": {
        "async": "^0.2.10",
        "cors": "^2.3.1",
        "ejs": "^0.8.8",
        "email-templates": "^1.2.1",
        "express": "^3.5.1",
        "jade": "^1.3.1",
        "jsonwebtoken": "5.0.0",
        "lodash": "2.4.1",
        "moment": "^2.6.0",
        "mongo-migrate": "afloyd/mongo-migrate",
        "mongodb": "~1.4.3",
        "mongoose": "~3.8.13",
        "node-schedule": "^0.1.13",
        "node-syslog": "^1.2.0",
        "node-uuid": "~1.4.1",
        "node.extend": "~1.0.9",
        "passport": "^0.1.18",
        "passport-local": "^0.1.6",
        "pm2": "^0.8.1",
        "q": "1.0.1",
        "redis": "~0.10.1",
        "sync": "~0.2.2"
    },
    "devDependencies": {
        "bench-rest": "latest",
        "bower": "^1.3.3",
        "chai": "^2.3.0",
        "commonjs": "0.0.1",
        "connect-flash": "~0.1.1",
        "dateformat": "~1.0.7-1.2.3",
        "debug": "1.0.4",
        "grunt": "^0.4.5",
        "grunt-bg-shell": "~2.3.1",
        "grunt-bower-install-simple": "^1.0.3",
        "grunt-cli": "~0.1.13",
        "grunt-concurrent": "^0.5.0",
        "grunt-contrib-clean": "~0.5.0",
        "grunt-contrib-jshint": "~0.11.0",
        "grunt-contrib-watch": "~0.5.3",
        "grunt-debug": "~0.0.3",
        "grunt-express": "~1.2.1",
        "grunt-express-server": "^0.4.13",
        "grunt-istanbul": "^0.5.0",
        "grunt-karma": "^0.8.3",
        "grunt-mocha-cov": "^0.4.0",
        "grunt-node-inspector": "^0.2.0",
        "grunt-nodemon": "^0.4.0",
        "grunt-npm-install": "^0.2.0",
        "grunt-open": "^0.2.3",
        "grunt-teamcity": "~0.1.3",
        "istanbul": "~0.2.4",
        "karma": "^0.12.32",
        "karma-chai": "^0.1.0",
        "karma-chrome-launcher": "^0.1.3",
        "karma-mocha": "^0.1.10",
        "karma-phantomjs-launcher": "^0.2.0",
        "karma-sinon": "^1.0.3",
        "karma-teamcity-reporter": "^0.1.2",
        "mocha": "^2.2.5",
        "mocha-lcov-reporter": "0.0.1",
        "mocha-teamcity-reporter": "0.0.2",
        "mocha-term-cov-reporter": "^0.2.0",
        "mockgoose": "^2.0.2",
        "node-mocks-http": "~1.0.1",
        "nodemailer": "^0.6.3",
        "phantomjs": "^1.9.8",
        "request": "~2.34.0",
        "requirejs": "~2.1.10",
        "sinon": "~1.8.2",
        "supertest": "~0.13.0",
        "zombie": "^3.0.0"
    },
    "config": {
        "blanket": {
            "pattern": "app/",
            "options": {
                "threshold": "70"
            }
        }
    },
    "bundledDependencies": [
        "express",
        "ejs",
        "node-uuid",
        "node.extend",
        "passport",
        "passport-local",
        "mongoose",
        "redis",
        "async",
        "sync",
        "mongodb",
        "mongo-migrate",
        "node-syslog"
    ]
}

The error appears to be coming from node-syslog / node-gyp trying to clean the build folder in the node-syslog folder. However, when I go directly to the cwd - /opt/buildagent/work/d86748d67b9c54a8/Product/src/node_modules/node-syslog and run the command manually - "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
the command returns fine. The error only occurs when you run the npm build command with the package.json.

**Comment by sam-github** [comment]
Are you root, or running with sudo? Is it possible that npm is dropping permissions before running node-gyp, and after dropping has insufficient permissions to cleanup?

**Comment by thxmike** [comment]
Yes, we are running in sudo

**Comment by sam-github** [comment]
npm install doesn't work well with sudo
