### ISSUE TITLE
Multiple syslog logger [Not Issue, but Question]

### ISSUE THREAD

**Issue by pjolep** [schamane/node-syslog#46]
Not sure where to ask, so will go thru this chanel:

Is it possible to have something like this:

----

 var SyslogInfo = require('node-syslog');
 var SyslogError = require('node-syslog');

 SyslogInfo.init("info-syslog", SyslogInfo.LOG_PID | SyslogInfo.LOG_ODELAY, SyslogInfo.LOG_LOCAL0);
 SyslogError.init("error-syslog", SyslogError.LOG_PID | SyslogError.LOG_ODELAY, SyslogError.LOG_LOCAL0);

---

So, I want like two separate streams writing to server syslog? I tried to make it, but looks to me I always have one instance that writes messages.

I if do:
SyslogInfo.log(SyslogInfo.LOG_INFO, "Node Syslog Module output " + new Date());

In syslog will be "error-syslog" as program name even if I used SyslogInfo, because SyslogError was last .init() call.

**Comment by bnoordhuis** [comment]
In your example, `SyslogInfo === SyslogError` due to the way the module system works in node.js.  Apart from that, syslog(3) (the C library function) is effectively a process-wide facility, you can't have two concurrent instances.
