### ISSUE TITLE
Not supprot Nodejs 4.0.x?

### ISSUE THREAD

**Issue by wueason** [schamane/node-syslog#51]
Environment:
OS X 10.10.5
Nodejs: 4.0.0
Python 2.7.10
Npm: 2.14.2

npm info it worked if it ends with ok
npm info using npm@2.14.2
npm info using node@v4.0.0
npm WARN package.json hello@1.0.0 No description
npm WARN package.json hello@1.0.0 No repository field.
npm WARN package.json hello@1.0.0 No README data
npm info package.json ain2@1.5.3 No license field.
npm info package.json bignum@0.11.0 license should be a valid SPDX license expression
npm info package.json loopback-connector-mysql@2.2.0 license should be a valid SPDX license expression
npm info package.json node-syslog@1.2.0 No license field.
npm info package.json q@1.4.1 license should be a valid SPDX license expression
npm info package.json node-schedule@0.2.9 No license field.
npm info attempt registry request try #1 at 19:19:25
npm http request GET https://registry.npmjs.org/node-syslog
npm http 304 https://registry.npmjs.org/node-syslog
npm info install node-syslog@1.2.0 into /Users/Eason/workspace/hello
npm info installOne node-syslog@1.2.0
npm info preuninstall node-syslog@1.2.0
npm info uninstall node-syslog@1.2.0
npm info postuninstall node-syslog@1.2.0
npm info preinstall node-syslog@1.2.0
npm info build /Users/Eason/workspace/hello/node_modules/node-syslog
npm info linkStuff node-syslog@1.2.0
npm info install node-syslog@1.2.0

> node-syslog@1.2.0 install /Users/Eason/workspace/hello/node_modules/node-syslog
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.1
gyp info using node@4.0.0 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Eason/workspace/hello/node_modules/node-syslog/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Eason/.node-gyp/4.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Eason/.node-gyp/4.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Eason/workspace/hello/node_modules/node-syslog',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:1:
In file included from ../node-syslog.h:13:
../compat.h:27:2: error: "Unsupported node.js version."
#error "Unsupported node.js version."
 ^
../compat.h:62:53: error: unknown type name 'FunctionCallback'; did you mean 'v8::FunctionCallback'?
                                                    FunctionCallback callback =
                                                    ^~~~~~~~~~~~~~~~
                                                    v8::FunctionCallback
/Users/Eason/.node-gyp/4.0.0/include/node/v8.h:3175:16: note: 'v8::FunctionCallback' declared here
typedef void (*FunctionCallback)(const FunctionCallbackInfo<Value>& info);
               ^
In file included from ../syslog.cc:1:
In file included from ../node-syslog.h:13:
../compat.h:123:47: error: unknown type name 'ArgumentType'
  inline explicit ReturnableHandleScope(const ArgumentType& args);
                                              ^
../compat.h:124:10: error: unknown type name 'ReturnType'
  inline ReturnType Return();
         ^
../compat.h:125:10: error: unknown type name 'ReturnType'
  inline ReturnType Return(bool value);
         ^
../compat.h:126:10: error: unknown type name 'ReturnType'
  inline ReturnType Return(intptr_t value);
         ^
../compat.h:127:10: error: unknown type name 'ReturnType'
  inline ReturnType Return(int value);
         ^
../compat.h:128:10: error: unknown type name 'ReturnType'
  inline ReturnType Return(double value);
         ^
../compat.h:129:10: error: unknown type name 'ReturnType'
  inline ReturnType Return(const char* value);
         ^
../compat.h:130:10: error: unknown type name 'ReturnType'
  inline ReturnType Return(v8::Local<v8::Value> value);
         ^
../compat.h:134:9: error: unknown type name 'ArgumentType'
  const ArgumentType& args_;
        ^
In file included from ../syslog.cc:1:
../node-syslog.h:23:12: error: no type named 'ReturnType' in namespace 'compat'
        static C::ReturnType init   (const C::ArgumentType& args);
               ~~~^
../node-syslog.h:23:40: error: no type named 'ArgumentType' in namespace 'compat'
        static C::ReturnType init   (const C::ArgumentType& args);
                                           ~~~^
../node-syslog.h:24:12: error: no type named 'ReturnType' in namespace 'compat'
        static C::ReturnType log (const C::ArgumentType& args);
               ~~~^
../node-syslog.h:24:37: error: no type named 'ArgumentType' in namespace 'compat'
        static C::ReturnType log (const C::ArgumentType& args);
                                        ~~~^
../node-syslog.h:25:12: error: no type named 'ReturnType' in namespace 'compat'
        static C::ReturnType setMask (const C::ArgumentType& args);
               ~~~^
../node-syslog.h:25:41: error: no type named 'ArgumentType' in namespace 'compat'
        static C::ReturnType setMask (const C::ArgumentType& args);
                                            ~~~^
../node-syslog.h:26:12: error: no type named 'ReturnType' in namespace 'compat'
        static C::ReturnType destroy (const C::ArgumentType& args);
               ~~~^
../node-syslog.h:26:41: error: no type named 'ArgumentType' in namespace 'compat'
        static C::ReturnType destroy (const C::ArgumentType& args);
                                            ~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/syslog/syslog.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Eason/workspace/hello/node_modules/node-syslog
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm info node-syslog@1.2.0 Failed to exec install script
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-syslog"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! node-syslog@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-syslog@1.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-syslog
npm ERR! There is likely additional logging output above.
npm info preuninstall node-syslog@1.2.0
npm info uninstall node-syslog@1.2.0
npm info postuninstall node-syslog@1.2.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Eason/workspace/hello/npm-debug.log

**Comment by vekexasia** [comment]
:( ?

**Comment by jeremycx** [comment]
Try https://github.com/strongloop/modern-syslog it's API-compatible, and, well, modern. :)
